export const NEW_APPLICATION_REQUEST = "NEW_APPLICATION_REQUEST";
export const NEW_APPLICATION_SUCCESS = "NEW_APPLICATION_SUCCESS";
export const NEW_APPLICATION_FAIL = "NEW_APPLICATION_FAIL";
export const NEW_APPLICATION_RESET = "NEW_APPLICATION_RESET";

export const GET_APPLICATIONS_REQUEST = "GET_APPLICATIONS_REQUEST";
export const GET_APPLICATIONS_SUCCESS = "GET_APPLICATIONS_SUCCESS";
export const GET_APPLICATIONS_FAIL = "GET_APPLICATIONS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
