export const GET_CHATS_REQUEST = 'GET_CHATS_REQUEST';
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
export const GET_CHATS_FAIL = 'GET_CHATS_FAIL';

export const GET_CHAT_DETAILS_REQUEST = 'GET_CHAT_DETAILS_REQUEST';
export const GET_CHAT_DETAILS_SUCCESS = 'GET_CHAT_DETAILS_SUCCESS';
export const GET_CHAT_DETAILS_FAIL = 'GET_CHAT_DETAILS_FAIL';

export const CREATE_OR_GET_CHAT_REQUEST = 'CREATE_OR_GET_CHAT_REQUEST';
export const CREATE_OR_GET_CHAT_SUCCESS = 'CREATE_OR_GET_CHAT_SUCCESS';
export const CREATE_OR_GET_CHAT_FAIL = 'CREATE_OR_GET_CHAT_FAIL';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const GET_ALL_USERS_IN_CHATS_REQUEST = 'GET_ALL_USERS_IN_CHATS_REQUEST';
export const GET_ALL_USERS_IN_CHATS_SUCCESS = 'GET_ALL_USERS_IN_CHATS_SUCCESS';
export const GET_ALL_USERS_IN_CHATS_FAIL = 'GET_ALL_USERS_IN_CHATS_FAIL';
