export const UPDATE_SHOP_SUCCESS = "UPDATE_SHOP_SUCCESS";
export const UPDATE_SHOP_FAIL = "UPDATE_SHOP_FAIL";
export const UPDATE_SHOP_RESET = "UPDATE_SHOP_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
